# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

fileSystems."/" =
  { device = "/dev/disk/by-uuid/0eaf838f-9dc8-4713-9b56-a31b201c3264";
    fsType = "ext4";
  };

fileSystems."/boot" =
  { device = "/dev/disk/by-uuid/6353-B6F3";
    fsType = "vfat";
    options = [ "fmask=0077" "dmask=0077" ];
  };

fileSystems."/mnt/games" = {
  device = "/dev/disk/by-uuid/14f84b4e-95f2-492e-b6b2-98e370084d3d";
  fsType = "ext4";
  options = [ "defaults" "nofail" ];
};

swapDevices =
  [ { device = "/dev/disk/by-uuid/a0061fb5-d826-4489-abeb-cfdb29fd76e8"; }
  ];
  
  
  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
